### ISSUE TITLE
Points are very unstable

### ISSUE THREAD

**Issue by robo-z** [ck-zhang/EyePy#7]
Hello, your job is really great! I have a question to ask. During the use of them, the coordinate points are very unstable, even if my eyes are not moving, how can I make the points more stable? I think this problem will also be encountered in your future work, mouse control.

I know this may be a common problem, also encountered in GazeRecorder, are there any clues to be improved?

**Comment by ck-zhang** [comment]
You can try the new updated demo, my solution to this problem is to add a **Kalman filter**, it's really great for smoothing stuff like this :) I do plan to also add an auto calibrating method for the filter (so that the prediction is smooth and *not* laggy), but for now you'll have to tweak the filter around a bit to make it work.

**Comment by robo-z** [comment]
Thanks a lot. I tried tuning up the processNoiseCov and measurementNoiseCov and it did became slightly more stable but maybe not enough. Expect you to make the prediction more stable.
